### ISSUE TITLE
Add support for `GeogTOWGS84GeoKey`

### ISSUE THREAD

**Issue by chrstphrbrns** [JuliaEarth/GeoTIFF.jl#21]
One of my geotiffs throws `ArgumentError: invalid value for Enum GeoKeyID: 2062`

Ref: https://trac.osgeo.org/geotiff/wiki/TOWGS84GeoKey

**Comment by eliascarv** [comment]
The GeoTIFF.jl package aims to implement only the GeoKeys defined in the OGC GeoTIFF specification: 
https://docs.ogc.org/is/19-008r4/19-008r4.html
Sorry for the delay in responding.
